name: Deploy MusicWeb

on:
  push:
    branches:
      - main
    paths:
      - "MusicWeb/**" # Chỉ chạy tự động khi có thay đổi trong thư mục MusicWeb

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: MusicWeb # Chỉ định chạy lệnh bên trong thư mục MusicWeb

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Hoặc phiên bản Node bạn đang dùng ở máy
          cache: "npm"
          cache-dependency-path: MusicWeb/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: MusicWeb/dist # Thư mục sản phẩm sau khi build của Vite
          branch: gh-pages
